In [1]:
import pandas as pd
import numpy as np
compound_df = pd.read_csv("F:\\MS\\SRH study\\IV sem\\INT\\Datasets 2023\\Natural Products-General Information.txt", sep='\t')
compound_df.head()

,np_id,pref_name,iupac_name,chembl_id,pubchem_cid,num_of_organism,num_of_target,num_of_activity,if_has_Quantity
0,NPC100002,Dibromomethane,dibromomethane,CHEMBL1229889,3024,4.0,1.0,3.0,No
1,NPC100005,MXFUWJQZQGWIOY-FETLVNPKSA-N,n.a.,n.a.,101412375,7.0,0.0,0.0,No
2,NPC100008,WPYIYVXSMXASQL-PEBLQZBPSA-N,n.a.,n.a.,14583329,16.0,0.0,0.0,No
3,NPC10001,LTNUWWZNTOSEML-SNLNFDIBSA-N,n.a.,n.a.,n.a.,1.0,4.0,4.0,No
4,NPC100016,KKFCJNGKHYRAPZ-MPCIYCNASA-N,n.a.,n.a.,n.a.,13.0,0.0,0.0,No

Data Cleaning

In [2]:
compound_df.replace('n.a.', np.nan, inplace=True)
compound_df

,np_id,pref_name,iupac_name,chembl_id,pubchem_cid,num_of_organism,num_of_target,num_of_activity,if_has_Quantity
0,NPC100002,Dibromomethane,dibromomethane,CHEMBL1229889,3024,4.0,1.0,3.0,No
1,NPC100005,MXFUWJQZQGWIOY-FETLVNPKSA-N,NaN,NaN,101412375,7.0,0.0,0.0,No
2,NPC100008,WPYIYVXSMXASQL-PEBLQZBPSA-N,NaN,NaN,14583329,16.0,0.0,0.0,No
3,NPC10001,LTNUWWZNTOSEML-SNLNFDIBSA-N,NaN,NaN,NaN,1.0,4.0,4.0,No
4,NPC100016,KKFCJNGKHYRAPZ-MPCIYCNASA-N,NaN,NaN,NaN,13.0,0.0,0.0,No
...,...,...,...,...,...,...,...,...,...
96415,NPC99965,WIRVPUPBTFGQDD-PWMZFVSCSA-N,NaN,NaN,NaN,25.0,0.0,0.0,No
96416,NPC99968,Egonol,"3-[2-(1,3-benzodioxol-5-yl)-7-methoxy-1-benzof...",CHEMBL470981,485186,37.0,13.0,19.0,No
96417,NPC99971,JANONPLUBJJWRY-QYVUEXTBSA-N,NaN,NaN,NaN,14.0,0.0,0.0,No
96418,NPC99991,OBNQCTKSFBMUDQ-UQOODKLHSA-N,NaN,NaN,NaN,3.0,0.0,0.0,No
96419,NPC99998,UYLHQHLKCSJVJP-WGSLJMJZSA-N,NaN,NaN,NaN,19.0,0.0,0.0,No

In [3]:
compound_df.isnull().sum()

np_id                  0
pref_name              0
iupac_name         73919
chembl_id          67624
pubchem_cid        22473
num_of_organism        1
num_of_target          1
num_of_activity        1
if_has_Quantity        1
dtype: int64

In [4]:
compound_data=compound_df.dropna()

In [5]:
compound_data

,np_id,pref_name,iupac_name,chembl_id,pubchem_cid,num_of_organism,num_of_target,num_of_activity,if_has_Quantity
0,NPC100002,Dibromomethane,dibromomethane,CHEMBL1229889,3024,4.0,1.0,3.0,No
10,NPC100039,4-Methylbenzaldehyde,4-methylbenzaldehyde,CHEMBL190927,7725,23.0,6.0,6.0,No
13,NPC10005,Olean-12(13)En-3Beta-Hexadecanoate,"[(3S,4aR,6aR,6bS,8aR,12aS,14aR,14bR)-4,4,6a,6b...",CHEMBL1170486,13915595,1.0,1.0,1.0,No
16,NPC100067,Kanzonol C,"(E)-1-[2,4-dihydroxy-3-(3-methylbut-2-enyl)phe...",CHEMBL1644933,5316802,6.0,13.0,27.0,No
20,NPC100079,Chelerythrine,"1,2-dimethoxy-12-methyl-[1,3]benzodioxolo[5,6-...",CHEMBL13045,2703,121.0,299.0,647.0,No
...,...,...,...,...,...,...,...,...,...
96394,NPC99909,Lucidumol A,"(5R,10S,13R,14R,17R)-17-[(2R,5S)-5,6-dihydroxy...",CHEMBL1917739,475410,2.0,3.0,4.0,No
96403,NPC99937,Arnamial,"[(2R,4S,4aR,7aS,7bR)-3-formyl-4-hydroxy-6,6,7b...",CHEMBL1078389,44557095,2.0,9.0,13.0,No
96404,NPC99939,"(R)-6',6''-Didebromohamacanthin B","(3R)-3,5-bis(1H-indol-3-yl)-2,3-dihydro-1H-pyr...",CHEMBL219235,16104844,1.0,14.0,25.0,No
96410,NPC99957,5-Hydroxy-6-Methoxy-2-Methylchromone-7-O-Rutin...,"5-hydroxy-6-methoxy-2-methyl-7-[(2S,3R,4S,5S,6...",CHEMBL564024,44139362,1.0,3.0,3.0,No
96416,NPC99968,Egonol,"3-[2-(1,3-benzodioxol-5-yl)-7-methoxy-1-benzof...",CHEMBL470981,485186,37.0,13.0,19.0,No

In [6]:
compound_data.isnull().sum()

np_id              0
pref_name          0
iupac_name         0
chembl_id          0
pubchem_cid        0
num_of_organism    0
num_of_target      0
num_of_activity    0
if_has_Quantity    0
dtype: int64

In [7]:
# Checking for duplicate np_id values
duplicates = compound_data[compound_data.duplicated(subset='np_id', keep=False)]
if not duplicates.empty:
    print("Duplicate np_id values found:")
    print(duplicates)
else:
    print("No duplicate np_id values found.")

No duplicate np_id values found.

Data formatting
--

In [8]:
compound_data.columns = [col.strip().lower() for col in compound_data.columns] #keeping column names standard

In [9]:
compound_data.columns

Index(['np_id', 'pref_name', 'iupac_name', 'chembl_id', 'pubchem_cid',
       'num_of_organism', 'num_of_target', 'num_of_activity',
       'if_has_quantity'],
      dtype='object')

In [10]:
compound_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20949 entries, 0 to 96416
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   np_id            20949 non-null  object
 1   pref_name        20949 non-null  object
 2   iupac_name       20949 non-null  object
 3   chembl_id        20949 non-null  object
 4   pubchem_cid      20949 non-null  object
 5   num_of_organism  20949 non-null  float64
 6   num_of_target    20949 non-null  float64
 7   num_of_activity  20949 non-null  float64
 8   if_has_quantity  20949 non-null  object
dtypes: float64(3), object(6)
memory usage: 1.6+ MB

In [11]:
compound_data

,np_id,pref_name,iupac_name,chembl_id,pubchem_cid,num_of_organism,num_of_target,num_of_activity,if_has_quantity
0,NPC100002,Dibromomethane,dibromomethane,CHEMBL1229889,3024,4.0,1.0,3.0,No
10,NPC100039,4-Methylbenzaldehyde,4-methylbenzaldehyde,CHEMBL190927,7725,23.0,6.0,6.0,No
13,NPC10005,Olean-12(13)En-3Beta-Hexadecanoate,"[(3S,4aR,6aR,6bS,8aR,12aS,14aR,14bR)-4,4,6a,6b...",CHEMBL1170486,13915595,1.0,1.0,1.0,No
16,NPC100067,Kanzonol C,"(E)-1-[2,4-dihydroxy-3-(3-methylbut-2-enyl)phe...",CHEMBL1644933,5316802,6.0,13.0,27.0,No
20,NPC100079,Chelerythrine,"1,2-dimethoxy-12-methyl-[1,3]benzodioxolo[5,6-...",CHEMBL13045,2703,121.0,299.0,647.0,No
...,...,...,...,...,...,...,...,...,...
96394,NPC99909,Lucidumol A,"(5R,10S,13R,14R,17R)-17-[(2R,5S)-5,6-dihydroxy...",CHEMBL1917739,475410,2.0,3.0,4.0,No
96403,NPC99937,Arnamial,"[(2R,4S,4aR,7aS,7bR)-3-formyl-4-hydroxy-6,6,7b...",CHEMBL1078389,44557095,2.0,9.0,13.0,No
96404,NPC99939,"(R)-6',6''-Didebromohamacanthin B","(3R)-3,5-bis(1H-indol-3-yl)-2,3-dihydro-1H-pyr...",CHEMBL219235,16104844,1.0,14.0,25.0,No
96410,NPC99957,5-Hydroxy-6-Methoxy-2-Methylchromone-7-O-Rutin...,"5-hydroxy-6-methoxy-2-methyl-7-[(2S,3R,4S,5S,6...",CHEMBL564024,44139362,1.0,3.0,3.0,No
96416,NPC99968,Egonol,"3-[2-(1,3-benzodioxol-5-yl)-7-methoxy-1-benzof...",CHEMBL470981,485186,37.0,13.0,19.0,No

Feature Engineering
--

In [12]:
compound_data['if_has_quantity'] = compound_data['if_has_quantity'].apply(lambda x: 1 if x == 'Yes' else 0)

C:\Users\Ayush\AppData\Local\Temp\ipykernel_24612\4152454267.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  compound_data['if_has_quantity'] = compound_data['if_has_quantity'].apply(lambda x: 1 if x == 'Yes' else 0)

In [13]:
compound_data

,np_id,pref_name,iupac_name,chembl_id,pubchem_cid,num_of_organism,num_of_target,num_of_activity,if_has_quantity
0,NPC100002,Dibromomethane,dibromomethane,CHEMBL1229889,3024,4.0,1.0,3.0,0
10,NPC100039,4-Methylbenzaldehyde,4-methylbenzaldehyde,CHEMBL190927,7725,23.0,6.0,6.0,0
13,NPC10005,Olean-12(13)En-3Beta-Hexadecanoate,"[(3S,4aR,6aR,6bS,8aR,12aS,14aR,14bR)-4,4,6a,6b...",CHEMBL1170486,13915595,1.0,1.0,1.0,0
16,NPC100067,Kanzonol C,"(E)-1-[2,4-dihydroxy-3-(3-methylbut-2-enyl)phe...",CHEMBL1644933,5316802,6.0,13.0,27.0,0
20,NPC100079,Chelerythrine,"1,2-dimethoxy-12-methyl-[1,3]benzodioxolo[5,6-...",CHEMBL13045,2703,121.0,299.0,647.0,0
...,...,...,...,...,...,...,...,...,...
96394,NPC99909,Lucidumol A,"(5R,10S,13R,14R,17R)-17-[(2R,5S)-5,6-dihydroxy...",CHEMBL1917739,475410,2.0,3.0,4.0,0
96403,NPC99937,Arnamial,"[(2R,4S,4aR,7aS,7bR)-3-formyl-4-hydroxy-6,6,7b...",CHEMBL1078389,44557095,2.0,9.0,13.0,0
96404,NPC99939,"(R)-6',6''-Didebromohamacanthin B","(3R)-3,5-bis(1H-indol-3-yl)-2,3-dihydro-1H-pyr...",CHEMBL219235,16104844,1.0,14.0,25.0,0
96410,NPC99957,5-Hydroxy-6-Methoxy-2-Methylchromone-7-O-Rutin...,"5-hydroxy-6-methoxy-2-methyl-7-[(2S,3R,4S,5S,6...",CHEMBL564024,44139362,1.0,3.0,3.0,0
96416,NPC99968,Egonol,"3-[2-(1,3-benzodioxol-5-yl)-7-methoxy-1-benzof...",CHEMBL470981,485186,37.0,13.0,19.0,0

In [14]:
compound_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20949 entries, 0 to 96416
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   np_id            20949 non-null  object
 1   pref_name        20949 non-null  object
 2   iupac_name       20949 non-null  object
 3   chembl_id        20949 non-null  object
 4   pubchem_cid      20949 non-null  object
 5   num_of_organism  20949 non-null  float64
 6   num_of_target    20949 non-null  float64
 7   num_of_activity  20949 non-null  float64
 8   if_has_quantity  20949 non-null  int64
dtypes: float64(3), int64(1), object(5)
memory usage: 1.6+ MB

In [15]:
compound_data = compound_data[(compound_data['pref_name'].str.contains('aspi')) | (compound_data['if_has_quantity'] == 1)]

In [16]:
compound_data

,np_id,pref_name,iupac_name,chembl_id,pubchem_cid,num_of_organism,num_of_target,num_of_activity,if_has_quantity
54,NPC100223,"5-[3-(1,3-Benzodioxol-5-Yl)-1,3,3A,4,6,6A-Hexa...","5-[3-(1,3-benzodioxol-5-yl)-1,3,3a,4,6,6a-hexa...",CHEMBL1904496,5204,11.0,63.0,66.0,1
72,NPC100312,2-Methylpyrazine,2-methylpyrazine,CHEMBL479791,7976,7.0,6.0,7.0,1
89,NPC100380,Cis-Jasmone,3-methyl-2-[(Z)-pent-2-enyl]cyclopent-2-en-1-one,CHEMBL2251602,1549018,10.0,4.0,7.0,1
105,NPC100445,1-Methyl-4-Prop-1-En-2-Ylcyclohexan-1-Ol,1-methyl-4-prop-1-en-2-ylcyclohexan-1-ol,CHEMBL3184678,8748,31.0,1.0,1.0,1
131,NPC100551,Salicylic Acid,2-hydroxybenzoic acid,CHEMBL424,338,130.0,110.0,560.0,1
...,...,...,...,...,...,...,...,...,...
95945,NPC98098,Maleic Acid,(Z)-but-2-enedioic acid,CHEMBL539648,444266,21.0,9.0,20.0,1
96023,NPC98356,5-O-Feruloylquinic Acid,"(1S,3R,4R,5R)-1,3,4-trihydroxy-5-[(E)-3-(4-hyd...",CHEMBL3526659,9799386,35.0,2.0,6.0,1
96201,NPC99088,Lycopene,"(6E,8E,10E,12E,14E,16E,18E,20E,22E,24E,26E)-2,...",CHEMBL501174,446925,135.0,14.0,43.0,1
96353,NPC99734,Ethinyl Estradiol,"(8R,9S,13S,14S,17R)-17-ethynyl-13-methyl-7,8,9...",CHEMBL691,5991,73.0,143.0,2088.0,1
96389,NPC99886,Anethole,1-methoxy-4-[(E)-prop-1-enyl]benzene,CHEMBL452630,637563,72.0,27.0,52.0,1

Natural Products-Structure
--

In [17]:
Structure_df = pd.read_csv('F:\\MS\\SRH study\\IV sem\\INT\\Datasets 2023\\Natural Products_StructureInfo.txt', sep='\t')
Structure_df

,np_id,InChI,InChIKey,SMILES
0,NPC81384,"InChI=1S/C8H20NO6P/c1-9(2,3)4-5-14-16(12,13)15...",SUHOQUVVVLNYQR-MRVPVSSYSA-N,OC[C@H](COP(=O)(OCC[N+](C)(C)C)[O-])O
1,NPC109991,InChI=1S/C24H21NO5/c1-3-13(2)21(24(29)30)25-12...,RVOHRYJJXCFNQS-YEJXKQKISA-N,CC[C@H](C)[C@H](C(=O)O)n1cc2C=C(C(=O)c3c(ccc(c...
2,NPC4649,InChI=1S/C20H20O7/c1-5-6-14(22)26-19-18(24-11(...,MHLKYRDXNNGAMX-WLMAVBAVSA-N,C/C=C/C(=O)O[C@H]1[C@H](c2c(ccc3ccc(=O)oc23)OC...
3,NPC90844,InChI=1S/C23H25NO3/c1-25-15-6-7-16-18(10-15)20...,NCVWJDISIZHFQS-AWEZNQCLSA-N,COc1ccc2c(c1)c1cc(c(cc1c1C[C@@H]3CCCN3Cc21)OC)OC
4,NPC18064,InChI=1S/C30H48O3/c1-18-10-15-30(25(32)33)17-1...,HNJKFVJZKCXLRL-SILQXMKOSA-N,CC1=CC[C@]2([C@H]([C@@H]1C)[C@H]1CC[C@H]3[C@@]...
...,...,...,...,...
96230,NPC490923,InChI=1S/C8H9NO2/c1-9-7-5-3-2-4-6(7)8(10)11/h2...,WVMBPWMAQDVZCM-UHFFFAOYSA-M,CNC1=CC=CC=C1C(=O)[O-]
96231,NPC478028,InChI=1S/C95H125N23O24S2/c1-7-48(4)78-93(139)1...,VXOKYTDMQDFAQT-VJFZWUEESA-N,CC[C@H](C)[C@H]1C(=O)N2CCC[C@H]2C(=O)NCC(=O)N[...
96232,NPC478029,InChI=1S/C96H127N23O24S2/c1-8-49(4)79-94(140)1...,DIYKCNUJDOKJCM-FZVOVPNHSA-N,CC[C@H](C)[C@H]1C(=O)N2CCC[C@H]2C(=O)NCC(=O)N[...
96233,NPC490681,InChI=1S/C9H9NO4/c11-8(12)5-10-7-4-2-1-3-6(7)9...,PJUXPMVQAZLJEX-UHFFFAOYSA-N,O=C(O)CNC1=CC=CC=C1C(=O)O
96234,NPC490916,InChI=1S/C9H9NO4/c11-8(12)5-10-7-4-2-1-3-6(7)9...,PJUXPMVQAZLJEX-UHFFFAOYSA-N,O=C(O)CNC1=CC=CC=C1C(=O)O

In [18]:
Structure_df.isnull().sum()

np_id       0
InChI       0
InChIKey    0
SMILES      0
dtype: int64

In [19]:
Structure_df.replace('n.a.', np.nan, inplace=True)
Structure_df

,np_id,InChI,InChIKey,SMILES
0,NPC81384,"InChI=1S/C8H20NO6P/c1-9(2,3)4-5-14-16(12,13)15...",SUHOQUVVVLNYQR-MRVPVSSYSA-N,OC[C@H](COP(=O)(OCC[N+](C)(C)C)[O-])O
1,NPC109991,InChI=1S/C24H21NO5/c1-3-13(2)21(24(29)30)25-12...,RVOHRYJJXCFNQS-YEJXKQKISA-N,CC[C@H](C)[C@H](C(=O)O)n1cc2C=C(C(=O)c3c(ccc(c...
2,NPC4649,InChI=1S/C20H20O7/c1-5-6-14(22)26-19-18(24-11(...,MHLKYRDXNNGAMX-WLMAVBAVSA-N,C/C=C/C(=O)O[C@H]1[C@H](c2c(ccc3ccc(=O)oc23)OC...
3,NPC90844,InChI=1S/C23H25NO3/c1-25-15-6-7-16-18(10-15)20...,NCVWJDISIZHFQS-AWEZNQCLSA-N,COc1ccc2c(c1)c1cc(c(cc1c1C[C@@H]3CCCN3Cc21)OC)OC
4,NPC18064,InChI=1S/C30H48O3/c1-18-10-15-30(25(32)33)17-1...,HNJKFVJZKCXLRL-SILQXMKOSA-N,CC1=CC[C@]2([C@H]([C@@H]1C)[C@H]1CC[C@H]3[C@@]...
...,...,...,...,...
96230,NPC490923,InChI=1S/C8H9NO2/c1-9-7-5-3-2-4-6(7)8(10)11/h2...,WVMBPWMAQDVZCM-UHFFFAOYSA-M,CNC1=CC=CC=C1C(=O)[O-]
96231,NPC478028,InChI=1S/C95H125N23O24S2/c1-7-48(4)78-93(139)1...,VXOKYTDMQDFAQT-VJFZWUEESA-N,CC[C@H](C)[C@H]1C(=O)N2CCC[C@H]2C(=O)NCC(=O)N[...
96232,NPC478029,InChI=1S/C96H127N23O24S2/c1-8-49(4)79-94(140)1...,DIYKCNUJDOKJCM-FZVOVPNHSA-N,CC[C@H](C)[C@H]1C(=O)N2CCC[C@H]2C(=O)NCC(=O)N[...
96233,NPC490681,InChI=1S/C9H9NO4/c11-8(12)5-10-7-4-2-1-3-6(7)9...,PJUXPMVQAZLJEX-UHFFFAOYSA-N,O=C(O)CNC1=CC=CC=C1C(=O)O
96234,NPC490916,InChI=1S/C9H9NO4/c11-8(12)5-10-7-4-2-1-3-6(7)9...,PJUXPMVQAZLJEX-UHFFFAOYSA-N,O=C(O)CNC1=CC=CC=C1C(=O)O

In [20]:
# Checking for duplicate np_id values
duplicates = Structure_df[Structure_df.duplicated(subset='np_id', keep=False)]
duplicate_count = duplicates['np_id'].nunique()  # Count unique duplicate np_id values

if not duplicates.empty:
    print("Duplicate np_id values found:")
    print(duplicates)
    print(f"Number of duplicate np_id values: {duplicate_count}")
else:
    print("No duplicate np_id values found.")

# Removing duplicate np_id values
Structure_df = Structure_df.drop_duplicates(subset='np_id', keep='first')

Structure_df

Duplicate np_id values found:
           np_id                                              InChI  \
94636  NPC477694  InChI=1S/C16H16O5/c17-11-2-1-3-12(18)16(11)13(...
94637  NPC477694  InChI=1S/C16H16O5/c17-11-2-1-3-12(18)16(11)13(...

                          InChIKey  \
94636  RPQDJLPVLPQRGX-UHFFFAOYSA-N
94637  RPQDJLPVLPQRGX-UHFFFAOYSA-N

                                            SMILES
94636  C1CC(=O)C(=C(CCC2=CC3=C(C=C2)OCO3)O)C(=O)C1
94637  C1CC(=O)C(=C(CCC2=CC3=C(C=C2)OCO3)O)C(=O)C1
Number of duplicate np_id values: 1

,np_id,InChI,InChIKey,SMILES
0,NPC81384,"InChI=1S/C8H20NO6P/c1-9(2,3)4-5-14-16(12,13)15...",SUHOQUVVVLNYQR-MRVPVSSYSA-N,OC[C@H](COP(=O)(OCC[N+](C)(C)C)[O-])O
1,NPC109991,InChI=1S/C24H21NO5/c1-3-13(2)21(24(29)30)25-12...,RVOHRYJJXCFNQS-YEJXKQKISA-N,CC[C@H](C)[C@H](C(=O)O)n1cc2C=C(C(=O)c3c(ccc(c...
2,NPC4649,InChI=1S/C20H20O7/c1-5-6-14(22)26-19-18(24-11(...,MHLKYRDXNNGAMX-WLMAVBAVSA-N,C/C=C/C(=O)O[C@H]1[C@H](c2c(ccc3ccc(=O)oc23)OC...
3,NPC90844,InChI=1S/C23H25NO3/c1-25-15-6-7-16-18(10-15)20...,NCVWJDISIZHFQS-AWEZNQCLSA-N,COc1ccc2c(c1)c1cc(c(cc1c1C[C@@H]3CCCN3Cc21)OC)OC
4,NPC18064,InChI=1S/C30H48O3/c1-18-10-15-30(25(32)33)17-1...,HNJKFVJZKCXLRL-SILQXMKOSA-N,CC1=CC[C@]2([C@H]([C@@H]1C)[C@H]1CC[C@H]3[C@@]...
...,...,...,...,...
96230,NPC490923,InChI=1S/C8H9NO2/c1-9-7-5-3-2-4-6(7)8(10)11/h2...,WVMBPWMAQDVZCM-UHFFFAOYSA-M,CNC1=CC=CC=C1C(=O)[O-]
96231,NPC478028,InChI=1S/C95H125N23O24S2/c1-7-48(4)78-93(139)1...,VXOKYTDMQDFAQT-VJFZWUEESA-N,CC[C@H](C)[C@H]1C(=O)N2CCC[C@H]2C(=O)NCC(=O)N[...
96232,NPC478029,InChI=1S/C96H127N23O24S2/c1-8-49(4)79-94(140)1...,DIYKCNUJDOKJCM-FZVOVPNHSA-N,CC[C@H](C)[C@H]1C(=O)N2CCC[C@H]2C(=O)NCC(=O)N[...
96233,NPC490681,InChI=1S/C9H9NO4/c11-8(12)5-10-7-4-2-1-3-6(7)9...,PJUXPMVQAZLJEX-UHFFFAOYSA-N,O=C(O)CNC1=CC=CC=C1C(=O)O
96234,NPC490916,InChI=1S/C9H9NO4/c11-8(12)5-10-7-4-2-1-3-6(7)9...,PJUXPMVQAZLJEX-UHFFFAOYSA-N,O=C(O)CNC1=CC=CC=C1C(=O)O

In [21]:
Structure_df.columns = [col.strip().lower() for col in Structure_df.columns] #keeping column names standard

In [22]:
Structure_df.columns

Index(['np_id', 'inchi', 'inchikey', 'smiles'], dtype='object')

In [23]:
Structure_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 96234 entries, 0 to 96234
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   np_id     96234 non-null  object
 1   inchi     96234 non-null  object
 2   inchikey  96234 non-null  object
 3   smiles    96234 non-null  object
dtypes: object(4)
memory usage: 3.7+ MB

In [24]:
merged_data = pd.merge(compound_data, Structure_df, on='np_id', suffixes=('_data1', '_data2'), how='inner')

In [25]:
Structure_data = ['np_id','inchi', 'inchikey','smiles']

In [26]:
Structure_data=merged_data[Structure_data]
Structure_data

,np_id,inchi,inchikey,smiles
0,NPC100223,InChI=1S/C20H18O6/c1-3-15-17(25-9-23-15)5-11(1...,PEYUIKBAABKQKQ-UHFFFAOYSA-N,c1cc2c(cc1C1C3COC(c4ccc5c(c4)OCO5)C3CO1)OCO2
1,NPC100312,"InChI=1S/C5H6N2/c1-5-4-6-2-3-7-5/h2-4H,1H3",CAWHJQAVHZEVTJ-UHFFFAOYSA-N,Cc1cnccn1
2,NPC100380,InChI=1S/C11H16O/c1-3-4-5-6-10-9(2)7-8-11(10)1...,XMLSXPIVAXONDL-PLNGDYQASA-N,CC/C=C\CC1=C(C)CCC1=O
3,NPC100445,"InChI=1S/C10H18O/c1-8(2)9-4-6-10(3,11)7-5-9/h9...",RUJPNZNXGCHGID-UHFFFAOYSA-N,C=C(C)C1CCC(C)(CC1)O
4,NPC100551,"InChI=1S/C7H6O3/c8-6-4-2-1-3-5(6)7(9)10/h1-4,8...",YGSDEFSMJLZEOE-UHFFFAOYSA-N,c1ccc(c(c1)C(=O)O)O
...,...,...,...,...
841,NPC98098,"InChI=1S/C4H4O4/c5-3(6)1-2-4(7)8/h1-2H,(H,5,6)...",VZCYOOQTPOCHFL-UPHRSURJSA-N,OC(=O)/C=C\C(=O)O
842,NPC98356,InChI=1S/C17H20O9/c1-25-12-6-9(2-4-10(12)18)3-...,RAGZUCNPTLULOL-KJJWLSQTSA-N,COc1cc(/C=C/C(=O)O[C@@H]2C[C@@](O)(C[C@H]([C@H...
843,NPC99088,InChI=1S/C40H56/c1-33(2)19-13-23-37(7)27-17-31...,OAIJSZIZWZSQBC-GYZMGTAESA-N,C/C(=C\C=C\C=C(\C=C\C=C(\C=C\C=C(\CCC=C(C)C)/C...
844,NPC99734,InChI=1S/C20H24O2/c1-3-20(22)11-9-18-17-6-4-13...,BFPYWIDHMRZLRN-SLHNCBLASA-N,C#C[C@]1(O)CC[C@@H]2[C@]1(C)CC[C@H]1[C@H]2CCc2...
845,NPC99886,InChI=1S/C10H12O/c1-3-4-9-5-7-10(11-2)8-6-9/h3...,RUVINXPYWBROJD-ONEGZZNKSA-N,C/C=C/c1ccc(cc1)OC

NAEB Dataset
--
Uses data
--

In [27]:
uses_data = pd.read_csv("F:\\MS\\SRH study\\IV sem\\INT\\Datasets 2023\\naeb\\data\\naeb_dump\\uses.csv")
uses_data

,id,species,tribe,source,pageno,use_category,use_subcategory,notes,rawsource
0,1,1,21,53,197,2,25.0,Liquid pitch mixed with mountain goat tallow a...,"Turner, Nancy J., 1973, The Ethnobotany of the..."
1,2,1,21,53,197,2,14.0,Infusion of bark taken for stomach ailments.,"Turner, Nancy J., 1973, The Ethnobotany of the..."
2,3,1,21,53,197,2,123.0,Liquid pitch mixed with mountain goat tallow a...,"Turner, Nancy J., 1973, The Ethnobotany of the..."
3,4,1,21,53,197,2,49.0,Infusion of bark taken for tuberculosis.,"Turner, Nancy J., 1973, The Ethnobotany of the..."
4,5,1,86,166,152,2,69.0,Bark and other plants used as a tonic.,"Gottesfeld, Leslie M. J., 1992, The Importance..."
...,...,...,...,...,...,...,...,...,...
44686,44687,4260,122,53,200,1,NaN,Plants eaten raw with eulachon grease.,"Turner, Nancy J., 1973, The Ethnobotany of the..."
44687,44688,4260,166,101,89,1,NaN,"Fleshy, whitish rhizomes formerly eaten raw.","Turner, Nancy J., John Thomas, Barry F. Carlso..."
44688,44689,4260,166,101,89,3,28.0,Leaves formerly used to trap herring spawn.,"Turner, Nancy J., John Thomas, Barry F. Carlso..."
44689,44690,4260,181,14,82,1,NaN,Leaves picked with attached herring spawn and ...,"Compton, Brian Douglas, 1993, Upper North Waka..."
44690,44691,4260,215,23,77,1,86.0,Fleshy roots and leaf bases used to flavor sea...,"Turner, Nancy Chapman and Marcus A. M. Bell, 1..."

Data cleaning
-----

In [28]:
uses_data.isnull().sum()

id                    0
species               0
tribe                 0
source                0
pageno                0
use_category          0
use_subcategory    3453
notes                 0
rawsource             0
dtype: int64

In [29]:
uses_data=uses_data.dropna()

In [30]:
uses_data.isnull().sum() #checking

id                 0
species            0
tribe              0
source             0
pageno             0
use_category       0
use_subcategory    0
notes              0
rawsource          0
dtype: int64

In [31]:

df_no_duplicates = uses_data.drop_duplicates(subset='use_subcategory', keep='first')
df_only_6 = uses_data[uses_data['use_subcategory'] == 6.0]
uses_data = pd.concat([df_no_duplicates, df_only_6]).drop_duplicates(keep=False)

uses_data

,id,species,tribe,source,pageno,use_category,use_subcategory,notes,rawsource
0,1,1,21,53,197,2,25.0,Liquid pitch mixed with mountain goat tallow a...,"Turner, Nancy J., 1973, The Ethnobotany of the..."
1,2,1,21,53,197,2,14.0,Infusion of bark taken for stomach ailments.,"Turner, Nancy J., 1973, The Ethnobotany of the..."
2,3,1,21,53,197,2,123.0,Liquid pitch mixed with mountain goat tallow a...,"Turner, Nancy J., 1973, The Ethnobotany of the..."
3,4,1,21,53,197,2,49.0,Infusion of bark taken for tuberculosis.,"Turner, Nancy J., 1973, The Ethnobotany of the..."
4,5,1,86,166,152,2,69.0,Bark and other plants used as a tonic.,"Gottesfeld, Leslie M. J., 1992, The Importance..."
...,...,...,...,...,...,...,...,...,...
44595,44596,4250,183,12,149150,2,6.0,Poultice of bulb used for rheumatic pains.,"Train, Percy, James R. Henrichs and W. Andrew ..."
44609,44610,4251,90,68,19,2,6.0,Roots or bulbs pounded with salt and the resul...,"Akana, Akaiko, 1922, Hawaiian Herbs of Medicin..."
44627,44628,4253,159,18,54,2,6.0,"Decoction of plant taken for stomachache, hear...","Vestal, Paul A., 1952, The Ethnobotany of the ..."
44655,44656,4256,139,21,250,2,6.0,Compound containing flower stalks used as snuf...,"Smith, Huron H., 1928, Ethnobotany of the Mesk..."
44668,44669,4258,193,11,50,2,6.0,Thorns used to prick the skin over rheumatic p...,"Curtin, L. S. M., 1949, By the Prophet of the ..."

In [32]:
uses_data

,id,species,tribe,source,pageno,use_category,use_subcategory,notes,rawsource
0,1,1,21,53,197,2,25.0,Liquid pitch mixed with mountain goat tallow a...,"Turner, Nancy J., 1973, The Ethnobotany of the..."
1,2,1,21,53,197,2,14.0,Infusion of bark taken for stomach ailments.,"Turner, Nancy J., 1973, The Ethnobotany of the..."
2,3,1,21,53,197,2,123.0,Liquid pitch mixed with mountain goat tallow a...,"Turner, Nancy J., 1973, The Ethnobotany of the..."
3,4,1,21,53,197,2,49.0,Infusion of bark taken for tuberculosis.,"Turner, Nancy J., 1973, The Ethnobotany of the..."
4,5,1,86,166,152,2,69.0,Bark and other plants used as a tonic.,"Gottesfeld, Leslie M. J., 1992, The Importance..."
...,...,...,...,...,...,...,...,...,...
44595,44596,4250,183,12,149150,2,6.0,Poultice of bulb used for rheumatic pains.,"Train, Percy, James R. Henrichs and W. Andrew ..."
44609,44610,4251,90,68,19,2,6.0,Roots or bulbs pounded with salt and the resul...,"Akana, Akaiko, 1922, Hawaiian Herbs of Medicin..."
44627,44628,4253,159,18,54,2,6.0,"Decoction of plant taken for stomachache, hear...","Vestal, Paul A., 1952, The Ethnobotany of the ..."
44655,44656,4256,139,21,250,2,6.0,Compound containing flower stalks used as snuf...,"Smith, Huron H., 1928, Ethnobotany of the Mesk..."
44668,44669,4258,193,11,50,2,6.0,Thorns used to prick the skin over rheumatic p...,"Curtin, L. S. M., 1949, By the Prophet of the ..."

In [33]:
uses_data.columns = [col.strip().lower() for col in uses_data.columns] #keeping column names standard

In [34]:
uses_data.columns

Index(['id', 'species', 'tribe', 'source', 'pageno', 'use_category',
       'use_subcategory', 'notes', 'rawsource'],
      dtype='object')

In [35]:
uses_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1679 entries, 0 to 44668
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1679 non-null   int64
 1   species          1679 non-null   int64
 2   tribe            1679 non-null   int64
 3   source           1679 non-null   int64
 4   pageno           1679 non-null   object
 5   use_category     1679 non-null   int64
 6   use_subcategory  1679 non-null   float64
 7   notes            1679 non-null   object
 8   rawsource        1679 non-null   object
dtypes: float64(1), int64(5), object(3)
memory usage: 131.2+ KB

In [36]:
uses_data

,id,species,tribe,source,pageno,use_category,use_subcategory,notes,rawsource
0,1,1,21,53,197,2,25.0,Liquid pitch mixed with mountain goat tallow a...,"Turner, Nancy J., 1973, The Ethnobotany of the..."
1,2,1,21,53,197,2,14.0,Infusion of bark taken for stomach ailments.,"Turner, Nancy J., 1973, The Ethnobotany of the..."
2,3,1,21,53,197,2,123.0,Liquid pitch mixed with mountain goat tallow a...,"Turner, Nancy J., 1973, The Ethnobotany of the..."
3,4,1,21,53,197,2,49.0,Infusion of bark taken for tuberculosis.,"Turner, Nancy J., 1973, The Ethnobotany of the..."
4,5,1,86,166,152,2,69.0,Bark and other plants used as a tonic.,"Gottesfeld, Leslie M. J., 1992, The Importance..."
...,...,...,...,...,...,...,...,...,...
44595,44596,4250,183,12,149150,2,6.0,Poultice of bulb used for rheumatic pains.,"Train, Percy, James R. Henrichs and W. Andrew ..."
44609,44610,4251,90,68,19,2,6.0,Roots or bulbs pounded with salt and the resul...,"Akana, Akaiko, 1922, Hawaiian Herbs of Medicin..."
44627,44628,4253,159,18,54,2,6.0,"Decoction of plant taken for stomachache, hear...","Vestal, Paul A., 1952, The Ethnobotany of the ..."
44655,44656,4256,139,21,250,2,6.0,Compound containing flower stalks used as snuf...,"Smith, Huron H., 1928, Ethnobotany of the Mesk..."
44668,44669,4258,193,11,50,2,6.0,Thorns used to prick the skin over rheumatic p...,"Curtin, L. S. M., 1949, By the Prophet of the ..."

Species data
--

In [37]:
species_fam_data = pd.read_csv("F:\\MS\\SRH study\\IV sem\\INT\\Datasets 2023\\naeb\\data\\naeb_dump\\species.csv")
species_fam_data

,id,name,common_names,usda_code,family,family_apg
0,1,Abies amabilis (Dougl. ex Loud.) Dougl. ex Forbes,Pacific Silver Fir,ABAM,Pinaceae,Pinaceae
1,2,Abies balsamea (L.) P. Mill.,Balsam Fir,ABBA,Pinaceae,Pinaceae
2,3,Abies concolor (Gord. & Glend.) Lindl. ex Hild...,White Fir,ABCOC,Pinaceae,Pinaceae
3,4,Abies fraseri (Pursh) Poir.,Fraser's Fir,ABFR,Pinaceae,Pinaceae
4,5,Abies grandis (Dougl. ex D. Don) Lindl.,Grand Fir,ABGRG,Pinaceae,Pinaceae
...,...,...,...,...,...,...
4255,4256,Zizia aurea (L.) W.D.J. Koch,Golden Zizia,ZIAU,Apiaceae,Apiaceae
4256,4257,Ziziphus obtusifolia (Hook. ex Torr. & Gray) Gray,Lotebush,ZIOBO,Rhamnaceae,Rhamnaceae
4257,4258,Ziziphus obtusifolia var. canescens (Gray) M.C...,Lotebush,ZIOBC,Rhamnaceae,Rhamnaceae
4258,4259,Ziziphus parryi Torr.,Parry's Jujube,ZIPA,Rhamnaceae,Rhamnaceae
4259,4260,Zostera marina L.,Seawrack,ZOMA,Zosteraceae,Zosteraceae

In [38]:
species_fam_data.isnull().sum()

id                0
name              0
common_names    112
usda_code       499
family            1
family_apg      198
dtype: int64

In [39]:
species_fam_data=species_fam_data.dropna()

In [40]:
# Check for duplicate np_id values
duplicates = species_fam_data[species_fam_data.duplicated(subset='id', keep=False)]
duplicate_count = duplicates['id'].nunique()  # Count unique duplicate np_id values

if not duplicates.empty:
    print("Duplicate np_id values found:")
    print(duplicates)
    print(f"Number of duplicate np_id values: {duplicate_count}")
else:
    print("No duplicate np_id values found.")

# Remove duplicate np_id values
species_fam_data = species_fam_data.drop_duplicates(subset='id', keep='first')

species_fam_data

No duplicate np_id values found.

,id,name,common_names,usda_code,family,family_apg
0,1,Abies amabilis (Dougl. ex Loud.) Dougl. ex Forbes,Pacific Silver Fir,ABAM,Pinaceae,Pinaceae
1,2,Abies balsamea (L.) P. Mill.,Balsam Fir,ABBA,Pinaceae,Pinaceae
2,3,Abies concolor (Gord. & Glend.) Lindl. ex Hild...,White Fir,ABCOC,Pinaceae,Pinaceae
3,4,Abies fraseri (Pursh) Poir.,Fraser's Fir,ABFR,Pinaceae,Pinaceae
4,5,Abies grandis (Dougl. ex D. Don) Lindl.,Grand Fir,ABGRG,Pinaceae,Pinaceae
...,...,...,...,...,...,...
4255,4256,Zizia aurea (L.) W.D.J. Koch,Golden Zizia,ZIAU,Apiaceae,Apiaceae
4256,4257,Ziziphus obtusifolia (Hook. ex Torr. & Gray) Gray,Lotebush,ZIOBO,Rhamnaceae,Rhamnaceae
4257,4258,Ziziphus obtusifolia var. canescens (Gray) M.C...,Lotebush,ZIOBC,Rhamnaceae,Rhamnaceae
4258,4259,Ziziphus parryi Torr.,Parry's Jujube,ZIPA,Rhamnaceae,Rhamnaceae
4259,4260,Zostera marina L.,Seawrack,ZOMA,Zosteraceae,Zosteraceae

In [41]:
merged_data = pd.merge(uses_data, species_fam_data, on='id', suffixes=('_data1', '_data2'), how='inner')

In [42]:
species_fam_data = ['id','name','common_names','usda_code','family','family_apg']

In [43]:
species_fam_data=merged_data[species_fam_data]
species_fam_data

,id,name,common_names,usda_code,family,family_apg
0,1,Abies amabilis (Dougl. ex Loud.) Dougl. ex Forbes,Pacific Silver Fir,ABAM,Pinaceae,Pinaceae
1,2,Abies balsamea (L.) P. Mill.,Balsam Fir,ABBA,Pinaceae,Pinaceae
2,3,Abies concolor (Gord. & Glend.) Lindl. ex Hild...,White Fir,ABCOC,Pinaceae,Pinaceae
3,4,Abies fraseri (Pursh) Poir.,Fraser's Fir,ABFR,Pinaceae,Pinaceae
4,5,Abies grandis (Dougl. ex D. Don) Lindl.,Grand Fir,ABGRG,Pinaceae,Pinaceae
...,...,...,...,...,...,...
260,4103,Veratrum californicum var. californicum,California False Hellebore,VECAC2,Liliaceae,Nartheciaceae
261,4129,Viburnum dentatum var. dentatum,Southern Arrowwood,VIDED4,Caprifoliaceae,Caprifoliaceae
262,4130,Viburnum edule (Michx.) Raf.,Mooseberry Viburnum,VIED,Caprifoliaceae,Caprifoliaceae
263,4136,Viburnum prunifolium L.,Blackhaw,VIPR,Caprifoliaceae,Caprifoliaceae
264,4143,Vicia nigricans ssp. gigantea (Hook.) Lassette...,Giant Vetch,VINIG,Fabaceae,Fabaceae

use_categories
--

In [44]:
use_categories_data = pd.read_csv('F:\\MS\\SRH study\\IV sem\\INT\\Datasets 2023\\naeb\\data\\naeb_dump\\use_categories.csv')
use_categories_data.head()

   id   name
0   1   Food
1   2   Drug
2   3  Other
3   4  Fiber
4   5    Dye

In [45]:
use_categories_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      5 non-null      int64
 1   name    5 non-null      object
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes

In [46]:
use_categories_data.columns = [col.strip().lower() for col in use_categories_data.columns] #keeping column names standard

In [47]:
use_categories_data.columns

Index(['id', 'name'], dtype='object')

In [48]:
use_categories_data

   id   name
0   1   Food
1   2   Drug
2   3  Other
3   4  Fiber
4   5    Dye

use subcategories
---

In [49]:
use_subcategories_data = pd.read_csv('F:\\MS\\SRH study\\IV sem\\INT\\Datasets 2023\\naeb\\data\\naeb_dump\\use_subcategories.csv')
use_subcategories_data.head()

   id  parent          name
0   1       1     Preserves
1   2       1  Bread & Cake
2   3       2    Kidney Aid
3   4       1    Dried Food
4   5       1        Forage

In [50]:
use_subcategories_data.isnull().sum()

id        0
parent    0
name      0
dtype: int64

In [51]:
use_subcategories_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 389 entries, 0 to 388
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      389 non-null    int64
 1   parent  389 non-null    int64
 2   name    389 non-null    object
dtypes: int64(2), object(1)
memory usage: 9.2+ KB

In [52]:
# Checking for duplicate target_id values
duplicates = use_subcategories_data[use_subcategories_data.duplicated(subset='id', keep=False)]
duplicate_count = duplicates['id'].nunique()  # Count unique duplicate np_id values

if not duplicates.empty:
    print("Duplicate id values found:")
    print(duplicates)
    print(f"Number of duplicate id values: {duplicate_count}")
else:
    print("No duplicate id values found.")

No duplicate id values found.

In [53]:
use_subcategories_data.columns = [col.strip().lower() for col in use_subcategories_data.columns] #keeping column names standard
use_subcategories_data

      id  parent          name
0      1       1     Preserves
1      2       1  Bread & Cake
2      3       2    Kidney Aid
3      4       1    Dried Food
4      5       1        Forage
..   ...     ...           ...
384  385       3  Preservative
385  386       3  Preservative
386  387       2   Dietary Aid
387  388       2   Dietary Aid
388  389       2   Dietary Aid

[389 rows x 3 columns]

In [54]:
pip install neo4j

In [55]:

from neo4j import GraphDatabase

uri = "bolt://localhost:7687" 
username = "neo4j"  # 
password = "Pan@1234"  

# Connecting to the Neo4j database
driver = GraphDatabase.driver(uri, auth=(username, password))

#nodes for compound
def create_nodes(tx, np_id, pref_name, iupac_name, chembl_id, pubchem_cid):
    tx.run(
        "CREATE (n:Compound {np_id: $np_id, pref_name: $pref_name, iupac_name: $iupac_name, chembl_id: $chembl_id, pubchem_cid: $pubchem_cid})",
        np_id=np_id,
        pref_name=pref_name,
        iupac_name=iupac_name,
        chembl_id=chembl_id,
        pubchem_cid=pubchem_cid
    )

for index, row in compound_data.iterrows():
    with driver.session() as session:
        session.write_transaction(create_nodes, row['np_id'], row['pref_name'], row['iupac_name'], row['chembl_id'], row['pubchem_cid'])
#########################################
# nodes for structure
def create_structure_nodes(tx, np_id, inchi, inchikey, smiles):
    tx.run("CREATE (:Structure {np_id: $np_id, inchi: $inchi, inchikey: $inchikey, smiles: $smiles})", 
           np_id=np_id, inchi=inchi, inchikey=inchikey, smiles=smiles)

with driver.session() as session:
    for index, row in Structure_data.iterrows():
        session.write_transaction(create_structure_nodes, row['np_id'], row['inchi'], row['inchikey'], row['smiles'])
####################################################################
#nodes for uses
# Function to create nodes
def create_uses_nodes(tx, id,species, tribe, source, page_no, use_category, use_subcategory, notes, raw_source):
    tx.run(
        "CREATE (:Usage {id: $id,species: $species, tribe: $tribe, source: $source, page_no: $page_no, use_category: $use_category, use_subcategory: $use_subcategory, notes: $notes, raw_source: $raw_source})",
        id=id,species=species, tribe=tribe, source=source, page_no=page_no, use_category=use_category, use_subcategory=use_subcategory, notes=notes, raw_source=raw_source
    )

with driver.session() as session:
    for index, row in uses_data.iterrows():
        session.write_transaction(create_uses_nodes,row['id'], row['species'], row['tribe'], row['source'], row['pageno'], row['use_category'], row['use_subcategory'], row['notes'], row['rawsource'])
##############################################################
#nodes for species

def create_species_nodes(tx, id,name, common_names, usda_code, family, family_apg):
    tx.run(
        "CREATE (:Species {id: $id,name: $name, common_names: $common_names, usda_code: $usda_code, family: $family, family_apg: $family_apg})",
        id=id,name=name, common_names=common_names, usda_code=usda_code, family=family, family_apg=family_apg
    )

with driver.session() as session:
    for index, row in species_fam_data.iterrows():
        session.write_transaction(create_species_nodes, row['id'], row['name'], row['common_names'], row['family'], row['usda_code'],row['family_apg'])

##############################################################
#nodes for use_category
def create_categories_nodes(tx, _id, name):
    tx.run(
        "CREATE (:UseCategory {id: $id, name: $name})",
        id=_id, name=name
    )

with driver.session() as session:
    for index, row in use_categories_data.iterrows():
        session.write_transaction(create_categories_nodes, row['id'], row['name'])
######################################################################

#node for use_subcategory
def create_usesubcategory_nodes(tx, _id, parent, name):
    tx.run(
        "CREATE (:UseSubcategory {id: $id, parent: $parent, name: $name})",
        id=_id, parent=parent, name=name
    )

with driver.session() as session:
    for index, row in use_subcategories_data.iterrows():
        session.write_transaction(create_usesubcategory_nodes, row['id'], row['parent'], row['name'])

C:\Users\Ayush\AppData\Local\Temp\ipykernel_24612\937644890.py:23: DeprecationWarning: write_transaction has been renamed to execute_write
  session.write_transaction(create_nodes, row['np_id'], row['pref_name'], row['iupac_name'], row['chembl_id'], row['pubchem_cid'])
C:\Users\Ayush\AppData\Local\Temp\ipykernel_24612\937644890.py:32: DeprecationWarning: write_transaction has been renamed to execute_write
  session.write_transaction(create_structure_nodes, row['np_id'], row['inchi'], row['inchikey'], row['smiles'])
C:\Users\Ayush\AppData\Local\Temp\ipykernel_24612\937644890.py:44: DeprecationWarning: write_transaction has been renamed to execute_write
  session.write_transaction(create_uses_nodes,row['id'], row['species'], row['tribe'], row['source'], row['pageno'], row['use_category'], row['use_subcategory'], row['notes'], row['rawsource'])
C:\Users\Ayush\AppData\Local\Temp\ipykernel_24612\937644890.py:56: DeprecationWarning: write_transaction has been renamed to execute_write
  session.write_transaction(create_species_nodes, row['id'], row['name'], row['common_names'], row['family'], row['usda_code'],row['family_apg'])
C:\Users\Ayush\AppData\Local\Temp\ipykernel_24612\937644890.py:68: DeprecationWarning: write_transaction has been renamed to execute_write
  session.write_transaction(create_categories_nodes, row['id'], row['name'])
C:\Users\Ayush\AppData\Local\Temp\ipykernel_24612\937644890.py:80: DeprecationWarning: write_transaction has been renamed to execute_write
  session.write_transaction(create_usesubcategory_nodes, row['id'], row['parent'], row['name'])

In [56]:
def create_compound_structure_relationship(tx):
    tx.run(
        """
        MATCH (c:Compound), (s:Structure)
        WHERE c.np_id = s.np_id
        CREATE (c)-[:Has_structure]->(s)
        """
    )
# Create relationships
with driver.session() as session:
    session.write_transaction(create_compound_structure_relationship)
################################################################
def create_usage_species_relationship(tx):
    tx.run(
        """
        MATCH (u:Usage), (sp:Species)
        WHERE u.species = sp.id
        CREATE (u)-[:Has_species_family]->(sp)
        """
    )
# Create relationships
with driver.session() as session:
    session.write_transaction(create_usage_species_relationship)
    
###############################################
def create_usage_category_relationship(tx):
    tx.run(
        """
        MATCH (u:Usage), (uc:UseCategory)
        WHERE u.use_category = uc.id
        CREATE (u)-[:Has_usage_category]->(uc)
        """
    )
# Create relationships
with driver.session() as session:
    session.write_transaction(create_usage_category_relationship)
    
####################################################################################

def create_usage_subcategory_relationship(tx):
    tx.run(
        """
        MATCH (u:Usage), (usc:UseSubcategory)
        WHERE u.use_subcategory = usc.id
        CREATE (u)-[:Has_usage_sub_category]->(usc)
        """
    )
# Create relationships
with driver.session() as session:
    session.write_transaction(create_usage_subcategory_relationship)
    
#########################################################################################

def create_usage_category__subcategory_relationship(tx):
    tx.run(
        """
        MATCH (uc:UseCategory), (usc:UseSubcategory)
        WHERE uc.id = usc.parent
        CREATE (uc)-[:Used_for]->(usc)
        """
    )
# Create relationships
with driver.session() as session:
    session.write_transaction(create_usage_category__subcategory_relationship)

C:\Users\Ayush\AppData\Local\Temp\ipykernel_24612\2456975038.py:11: DeprecationWarning: write_transaction has been renamed to execute_write
  session.write_transaction(create_compound_structure_relationship)
C:\Users\Ayush\AppData\Local\Temp\ipykernel_24612\2456975038.py:23: DeprecationWarning: write_transaction has been renamed to execute_write
  session.write_transaction(create_usage_species_relationship)
C:\Users\Ayush\AppData\Local\Temp\ipykernel_24612\2456975038.py:36: DeprecationWarning: write_transaction has been renamed to execute_write
  session.write_transaction(create_usage_category_relationship)
C:\Users\Ayush\AppData\Local\Temp\ipykernel_24612\2456975038.py:50: DeprecationWarning: write_transaction has been renamed to execute_write
  session.write_transaction(create_usage_subcategory_relationship)
C:\Users\Ayush\AppData\Local\Temp\ipykernel_24612\2456975038.py:64: DeprecationWarning: write_transaction has been renamed to execute_write
  session.write_transaction(create_usage_category__subcategory_relationship)